"""add road infra models

Revision ID: 3a8fa3b0076a
Revises: 5377a98d850e
Create Date: 2025-02-17 22:39:27.403952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8fa3b0076a'
down_revision = '5377a98d850e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashcam_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashcam_id', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lane_deviation', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('road_assessment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=False),
    sa.Column('additional_notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('total_alerts', sa.Integer(), nullable=False),
    sa.Column('alerts_summary', sa.String(length=255), nullable=True),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('road_assessment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('faded', sa.Boolean(), nullable=True),
    sa.Column('broken', sa.Boolean(), nullable=True),
    sa.Column('missing', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['road_assessment_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_assessment_reports')
    op.drop_table('safety_reports')
    op.drop_table('road_assessment_requests')
    op.drop_table('dashcam_alerts')
    # ### end Alembic commands ###
