name: lanify-dev
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: lanify-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: lanify-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - lanify_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: lanify-mlflow
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
      - ./mlflow.db:/mlflow.db

volumes:
  lanify_db_data:
