name: lanify-dev
services:
<<<<<<<< HEAD:dev/docker/sreehari-dev.yml
  backend:
    image: sreeharidev/lanify-backend:latest
    container_name: lanify-backend
========
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: lanify-app
>>>>>>>> f9d5d9b6fa2a6469422be09b5540484400eba8de:dev/docker/docker-compose.yml
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lanify
    depends_on:
      - db

<<<<<<<< HEAD:dev/docker/sreehari-dev.yml
  frontend:
    image: sreeharidev/lanify-frontend:latest
    container_name: lanify-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

========
>>>>>>>> f9d5d9b6fa2a6469422be09b5540484400eba8de:dev/docker/docker-compose.yml
  db:
    image: postgres:17
    container_name: lanify-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lanify
    volumes:
      - lanify_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  lanify_db_data:
