name: lanify-dev
services:
  backend:
    image: sreeharidev/lanify-backend:latest
    container_name: lanify-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lanify
    depends_on:
      - db

  frontend:
    image: sreeharidev/lanify-frontend:latest
    container_name: lanify-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: lanify-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lanify
    volumes:
      - lanify_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  lanify_db_data:
